Role: coordinator
Nodeaddr: localhost:3000
Followers: [localhost:3001, localhost:3002]

# follower #1
#Role: follower
#Nodeaddr: "localhost:3001"

# follower #2
#Role: follower
#Nodeaddr: "localhost:3002"