Role: coordinator
Nodeaddr: localhost:3000
Followers: ["192.168.0.101:3999"]

# follower #1
#Role: follower
#Nodeaddr: "localhost:3001"

# follower #2
#Role: follower
#Nodeaddr: "localhost:3002"

# allowed hosts
#whitelist: ["192.168.0.101"]