committype: three-phase
timeout: 1000 # ms, timeout after which the message is considered unacknowledged (only for three-phase mode, because two-phase is blocking by design)

Role: coordinator
Nodeaddr: localhost:3000
Followers: ["192.168.0.101:3999"]

# follower #1
#Role: follower
#Nodeaddr: "localhost:3001"

# follower #2
#Role: follower
#Nodeaddr: "localhost:3002"

# allowed hosts
#whitelist: ["192.168.0.101"]